import Foundation

extension Strings {
    static let de: [String: String] = [
        "lang.system": "System",

        "violation.over.title": "Ladegerät abziehen",
        "violation.under.title": "Ladegerät anschließen",
        "violation.over.instruction": "Der Akku hat die %d-%%-Grenze erreicht. Ziehe dein MacBook jetzt vom Strom, um die Akkulebensdauer zu schützen.",
        "violation.under.instruction": "Der Akku ist unter die %d-%%-Grenze gefallen. Tiefentladung schadet den Zellen – schließe dein MacBook jetzt ans Netz an.",

        "gauge.safe": "sicherer Bereich",
        "state.held": "Gehalten",
        "state.safe": "Sicher",
        "state.warned": "Warnung",
        "state.enforcing": "Sperre",
        "timeline.detect": "Abweichung",
        "timeline.warn": "Warnung · einmal",
        "timeline.enforce": "Sperre",
        "countdown.remaining": "übrig",

        "menubar.tooltip.safe": "Akku im sicheren Bereich (%d–%d %%)",
        "menu.settings": "Einstellungen …",
        "menu.onboarding": "Einführung anzeigen",
        "menu.quit": "Beenden",

        "panel.title": "Battery Longer",
        "panel.healthy.charging.room": "Am Netzteil, lädt. Noch %d Punkte bis zur %d-%%-Grenze.",
        "panel.healthy.charging.atLimit": "Am Netzteil. An der %d-%%-Grenze – bald Zeit zum Abziehen.",
        "panel.healthy.held": "Am Netzteil, lädt nicht (von macOS gehalten). Alles gut.",
        "panel.healthy.battery": "Im Akkubetrieb. %d Punkte über der %d-%%-Grenze.",
        "panel.warned.body": "Dies ist die einzige Warnung. Läuft die Zeit ab, wird der Bildschirm gesperrt.",
        "panel.enforcing.title": "Bildschirm gesperrt · %@",
        "panel.enforcing.body": "Seit %@. Nur das Beheben des Akkuzustands entsperrt.",
        "stat.source": "Quelle",
        "stat.source.adapter": "Netzteil",
        "stat.source.battery": "Akku",
        "stat.time": "Zeit",
        "stat.cycles": "Zyklen",
        "stat.health": "Zustand",
        "panel.settings": "Einstellungen",
        "panel.rule.summary": "Regel %d–%d %% · Frist %@",
        "panel.stats": "%d Warnungen · %d Sperren",
        "panel.quit": "Beenden",
        "panel.quit.help": "App beenden",
        "panel.quit.help.locked": "Beenden ist während der Sperre deaktiviert",

        "blocker.hint.over": "Dieser Bildschirm schließt sich von selbst, sobald das Kabel gezogen ist.",
        "blocker.hint.under": "Dieser Bildschirm schließt sich von selbst, sobald das Netzteil angeschlossen ist.",
        "blocker.emergency.idle": "Notausgang · 5 s halten",
        "blocker.emergency.holding": "Weiter halten … %d",
        "blocker.emergency.note": "Beendet die App vollständig. Nicht die Regel.",

        "onb.1.eyebrow": "Die Regel",
        "onb.1.title": "Zwischen 20 % und 80 % leben",
        "onb.1.body": "Lithium-Ionen-Akkus altern an den Extremen. Dauerhaft 100 % und Entladen auf 0 % verbrauchen die chemische Lebensdauer der Zellen. Diese App hält deinen Akku im sicheren Band.",
        "onb.1.b1": "Bei 80 % am Netzteil → abziehen",
        "onb.1.b2": "Bei 20 % im Akkubetrieb → anschließen",
        "onb.1.b3": "In engem Rahmen einstellbar; kein Verhandeln",
        "onb.2.eyebrow": "Schritt 1",
        "onb.2.title": "Eine Warnung, zwei Minuten",
        "onb.2.body": "Sobald du die Grenze überschreitest, wird die Menüleiste orange, eine einzelne Mitteilung erscheint und ein 2:00-Countdown startet. Keine zweite Warnung, kein Schlummern.",
        "onb.2.b1": "Eine Mitteilung, ein Ton",
        "onb.2.b2": "Live-Countdown in der Menüleiste",
        "onb.2.b3": "Rechtzeitig beheben – und nichts passiert",
        "onb.3.eyebrow": "Schritt 2",
        "onb.3.title": "Dann wird durchgesetzt",
        "onb.3.body": "Zwei Minuten vorbei und noch immer außerhalb? Alle Bildschirme werden gesperrt. Es gibt keinen Schließen-Knopf. Sobald du abziehst (oder anschließt), hebt sich die Sperre von selbst.",
        "onb.3.b1": "Auf jedem Display, in jedem Space",
        "onb.3.b2": "App-Wechsel deaktiviert",
        "onb.3.b3": "Einziger Ausweg: Akku zurück in den Bereich",
        "onb.4.eyebrow": "Ergebnis",
        "onb.4.title": "Jahre gesunder Akku",
        "onb.4.body": "Die Disziplin wirkt mühsam, aber Akkus im 20–80-Band liefern ein Vielfaches an Zyklen gegenüber Voll-zu-Leer-Betrieb. Dein MacBook soll auch in Jahren noch stundenlang durchhalten.",
        "onb.4.b1": "Läuft nur auf MacBooks",
        "onb.4.b2": "Lebt in der Menüleiste, kein Dock-Symbol",
        "onb.4.b3": "Mitteilungsberechtigung: damit du die Warnung siehst",
        "onb.back": "Zurück",
        "onb.next": "Weiter",
        "onb.finish": "Verstanden, schütze mich",

        "settings.title": "Battery Longer – Einstellungen",
        "settings.rule": "Regel",
        "settings.rule.low": "Untere Grenze",
        "settings.rule.low.desc": "Im Akkubetrieb bei diesem Stand → anschließen",
        "settings.rule.high": "Obere Grenze",
        "settings.rule.high.desc": "Am Netzteil bei diesem Stand → abziehen",
        "settings.rule.note": "Empfohlen und Standard: %d–%d %%. Das Band muss mindestens %d Punkte breit sein.",
        "settings.rule.reset": "Auf Standard zurücksetzen",
        "settings.timing": "Frist",
        "settings.timing.grace": "Von Warnung bis Sperre",
        "settings.timing.grace.desc": "1 – 10 Minuten in 30-s-Schritten. Standard 2:00.",
        "settings.timing.active": "Eine Warnung ist aktiv; die neue Frist gilt ab der nächsten.",
        "settings.warning": "Warnung",
        "settings.warning.sound": "Ton abspielen",
        "settings.warning.sound.desc": "Ein einzelner Systemton; danach Stille.",
        "settings.warning.panel": "Panel automatisch öffnen",
        "settings.warning.panel.desc": "Das Menüleisten-Panel erscheint mit dem Countdown.",
        "settings.warning.permission": "Mitteilungsberechtigung",
        "settings.warning.permission.desc": "Für die Warnmitteilung ist eine macOS-Berechtigung nötig.",
        "settings.warning.openSystem": "Systemeinstellungen öffnen",
        "settings.enforce": "Durchsetzung",
        "settings.enforce.sleep": "Mac bei Sperre an der unteren Grenze in den Ruhezustand versetzen",
        "settings.enforce.sleep.desc": "4 s nach Erscheinen der Sperre geht das System in den Ruhezustand; die Restladung bleibt erhalten.",
        "settings.enforce.snooze": "Schlummern / zweite Warnung",
        "settings.enforce.snooze.desc": "Absichtlich nicht vorhanden. Der einzige Ausweg ist der Akku zurück im Bereich.",
        "settings.enforce.off": "Aus",
        "settings.general": "Allgemein",
        "settings.general.login": "Bei der Anmeldung starten",
        "settings.general.login.desc": "Schutz besteht nur, solange die App läuft.",
        "settings.general.percent": "Prozent in der Menüleiste anzeigen",
        "settings.general.percent.desc": "Aus: nur Symbol; der Countdown bleibt bei Warnung und Sperre sichtbar.",
        "settings.general.language": "Sprache",
        "settings.general.onboarding": "Einführung",
        "settings.general.onboarding.show": "Erneut anzeigen",
        "settings.stats": "Statistik",
        "settings.stats.warnings": "Warnungen",
        "settings.stats.locks": "Sperren",
        "settings.stats.reset": "Zähler zurücksetzen",
        "settings.footer": "Battery Longer %@ · Nur MacBook",

        "banner.eyebrow": "Einführung",
        "banner.title": "So funktioniert Battery Longer",
        "banner.subtitle": "Die 20–80-Regel, die einzige Warnung und die Sperre – eine einminütige Tour in Skizzen.",
        "banner.cta": "Tour starten",
        "about": "Über",
        "about.author": "Entwickler",
        "about.company": "Unternehmen",
        "about.source": "Quellcode",

        "notif.warn.title": "Battery Longer • %@",
        "notif.warn.subtitle": "Akku %d %%",
        "notif.warn.body": "%@ Wird das nicht innerhalb von %@ behoben, wird der Bildschirm gesperrt.",
        "notif.resolved.title": "Battery Longer • Danke",
        "notif.resolved.body": "Der Akku ist zurück im sicheren Bereich (%d %%).",

        "alert.notMacBook.title": "Diese App läuft nur auf MacBooks",
        "alert.notMacBook.body": "Erkanntes Gerät: %@. Kein interner Akku gefunden; die 20–80-Regel ist auf Desktop-Macs sinnlos. Die App wird beendet.",
        "alert.close": "Schließen",
    ]
}
