import Foundation

extension Strings {
    static let fr: [String: String] = [
        "lang.system": "Système",

        "violation.over.title": "Débranchez le chargeur",
        "violation.under.title": "Branchez le chargeur",
        "violation.over.instruction": "La batterie a atteint la limite de %d %%. Débranchez votre MacBook maintenant pour préserver sa batterie.",
        "violation.under.instruction": "La batterie est passée sous la limite de %d %%. Une décharge profonde abîme les cellules : branchez votre MacBook maintenant.",

        "gauge.safe": "zone sûre",
        "state.held": "Maintenu",
        "state.safe": "Sûr",
        "state.warned": "Alerte",
        "state.enforcing": "Verrou",
        "timeline.detect": "Écart",
        "timeline.warn": "Alerte · unique",
        "timeline.enforce": "Verrou",
        "countdown.remaining": "restant",

        "menubar.tooltip.safe": "Batterie dans la zone sûre (%d–%d %%)",
        "menu.settings": "Réglages…",
        "menu.onboarding": "Afficher l'introduction",
        "menu.quit": "Quitter",

        "panel.title": "Battery Longer",
        "panel.healthy.charging.room": "Sur secteur, en charge. %d points avant la limite de %d %%.",
        "panel.healthy.charging.atLimit": "Sur secteur. À la limite de %d %% : il est presque temps de débrancher.",
        "panel.healthy.held": "Sur secteur, sans charge (maintenu par macOS). Tout va bien.",
        "panel.healthy.battery": "Sur batterie. %d points au-dessus de la limite de %d %%.",
        "panel.warned.body": "C'est la seule alerte. Quand le temps est écoulé, l'écran se verrouille.",
        "panel.enforcing.title": "Écran verrouillé · %@",
        "panel.enforcing.body": "Depuis %@. Seule la correction de la batterie déverrouille.",
        "stat.source": "Source",
        "stat.source.adapter": "Secteur",
        "stat.source.battery": "Batterie",
        "stat.time": "Durée",
        "stat.cycles": "Cycles",
        "stat.health": "Santé",
        "panel.settings": "Réglages",
        "panel.rule.summary": "Règle %d–%d %% · délai %@",
        "panel.stats": "%d alertes · %d verrous",
        "panel.quit": "Quitter",
        "panel.quit.help": "Quitter l'app",
        "panel.quit.help.locked": "Impossible de quitter pendant le verrou",

        "blocker.hint.over": "Cet écran disparaît de lui-même dès que le câble est retiré.",
        "blocker.hint.under": "Cet écran disparaît de lui-même dès que l'adaptateur est branché.",
        "blocker.emergency.idle": "Sortie d'urgence · maintenir 5 s",
        "blocker.emergency.holding": "Maintenez… %d",
        "blocker.emergency.note": "Ceci quitte complètement l'app. Pas la règle.",

        "onb.1.eyebrow": "La règle",
        "onb.1.title": "Vivre entre 20 % et 80 %",
        "onb.1.body": "Les batteries lithium-ion vieillissent aux extrêmes. Rester à 100 % et descendre à 0 % épuise la durée de vie chimique des cellules. Cette app confine votre batterie dans la zone sûre.",
        "onb.1.b1": "À 80 % sur secteur → débrancher",
        "onb.1.b2": "À 20 % sur batterie → brancher",
        "onb.1.b3": "Ajustable dans une plage étroite ; pas de négociation",
        "onb.2.eyebrow": "Étape 1",
        "onb.2.title": "Une alerte, deux minutes",
        "onb.2.body": "Dès que vous franchissez la limite, la barre des menus passe à l'orange, une seule notification arrive et un compte à rebours de 2:00 démarre. Pas de seconde alerte, pas de report.",
        "onb.2.b1": "Une notification, un son",
        "onb.2.b2": "Compte à rebours en direct dans la barre des menus",
        "onb.2.b3": "Corrigez à temps et rien ne se passe",
        "onb.3.eyebrow": "Étape 2",
        "onb.3.title": "Puis ça verrouille",
        "onb.3.body": "Deux minutes écoulées et toujours hors zone ? Tous les écrans se verrouillent. Aucun bouton pour fermer. Dès que vous débranchez (ou branchez), le verrou se lève tout seul.",
        "onb.3.b1": "Sur chaque écran, chaque Space",
        "onb.3.b2": "Changement d'app désactivé",
        "onb.3.b3": "Seule sortie : la batterie revient dans la zone",
        "onb.4.eyebrow": "Résultat",
        "onb.4.title": "Des années de batterie saine",
        "onb.4.body": "La discipline paraît fastidieuse, mais une batterie maintenue entre 20 et 80 % offre bien plus de cycles qu'une batterie vidée puis remplie. Que votre MacBook tienne encore des heures dans quelques années.",
        "onb.4.b1": "Fonctionne uniquement sur MacBook",
        "onb.4.b2": "Vit dans la barre des menus, pas d'icône dans le Dock",
        "onb.4.b3": "Autorisation de notification : pour voir l'alerte",
        "onb.back": "Retour",
        "onb.next": "Suivant",
        "onb.finish": "Compris, protège-moi",

        "settings.title": "Réglages de Battery Longer",
        "settings.rule": "Règle",
        "settings.rule.low": "Limite basse",
        "settings.rule.low.desc": "Sur batterie, à ce niveau → brancher",
        "settings.rule.high": "Limite haute",
        "settings.rule.high.desc": "Sur secteur, à ce niveau → débrancher",
        "settings.rule.note": "Recommandé et par défaut : %d–%d %%. La plage doit faire au moins %d points.",
        "settings.rule.reset": "Rétablir les valeurs par défaut",
        "settings.timing": "Délai",
        "settings.timing.grace": "De l'alerte au verrou",
        "settings.timing.grace.desc": "1 à 10 minutes par pas de 30 s. Par défaut 2:00.",
        "settings.timing.active": "Une alerte est en cours ; le nouveau délai s'appliquera à la prochaine.",
        "settings.warning": "Alerte",
        "settings.warning.sound": "Jouer un son",
        "settings.warning.sound.desc": "Un seul son système ; silence ensuite.",
        "settings.warning.panel": "Ouvrir le panneau automatiquement",
        "settings.warning.panel.desc": "Le panneau de la barre des menus apparaît avec le compte à rebours.",
        "settings.warning.permission": "Autorisation de notification",
        "settings.warning.permission.desc": "macOS doit autoriser la notification d'alerte.",
        "settings.warning.openSystem": "Ouvrir Réglages Système",
        "settings.enforce": "Verrou",
        "settings.enforce.sleep": "Mettre le Mac en veille lors d'un verrou bas",
        "settings.enforce.sleep.desc": "4 s après l'apparition du verrou, le système se met en veille ; la charge restante est préservée.",
        "settings.enforce.snooze": "Report / seconde alerte",
        "settings.enforce.snooze.desc": "Aucun, par conception. La seule issue est le retour de la batterie dans la zone.",
        "settings.enforce.off": "Désactivé",
        "settings.general": "Général",
        "settings.general.login": "Lancer à l'ouverture de session",
        "settings.general.login.desc": "La protection n'existe que si l'app est en cours d'exécution.",
        "settings.general.percent": "Afficher le pourcentage dans la barre des menus",
        "settings.general.percent.desc": "Icône seule si désactivé ; le compte à rebours reste visible pendant alertes et verrous.",
        "settings.general.language": "Langue",
        "settings.general.onboarding": "Introduction",
        "settings.general.onboarding.show": "Revoir",
        "settings.stats": "Statistiques",
        "settings.stats.warnings": "Alertes",
        "settings.stats.locks": "Verrous",
        "settings.stats.reset": "Réinitialiser les compteurs",
        "settings.footer": "Battery Longer %@ · MacBook uniquement",

        "banner.eyebrow": "Introduction",
        "banner.title": "Comment fonctionne Battery Longer",
        "banner.subtitle": "La règle 20–80, l'alerte unique et le verrou — une visite d'une minute en croquis.",
        "banner.cta": "Lancer la visite",
        "about": "À propos",
        "about.author": "Développeur",
        "about.company": "Entreprise",
        "about.source": "Code source",

        "notif.warn.title": "Battery Longer • %@",
        "notif.warn.subtitle": "Batterie %d %%",
        "notif.warn.body": "%@ Sans correction dans %@, l'écran se verrouille.",
        "notif.resolved.title": "Battery Longer • Merci",
        "notif.resolved.body": "La batterie est revenue dans la zone sûre (%d %%).",

        "alert.notMacBook.title": "Cette app ne fonctionne que sur MacBook",
        "alert.notMacBook.body": "Appareil détecté : %@. Aucune batterie interne ; la règle 20–80 n'a pas de sens sur un Mac de bureau. L'app va quitter.",
        "alert.close": "Fermer",
    ]
}
