import Foundation

extension Strings {
    static let tr: [String: String] = [
        "lang.system": "Sistem",

        "violation.over.title": "Şarj aletini çıkar",
        "violation.under.title": "Şarj aletini tak",
        "violation.over.instruction": "Pil %%%d sınırına ulaştı. Pil ömrünü korumak için MacBook'u şimdi fişten çek.",
        "violation.under.instruction": "Pil %%%d sınırının altına indi. Derin deşarj hücrelere zarar verir, MacBook'u şimdi şarja tak.",

        "gauge.safe": "güvenli aralık",
        "state.held": "Tutuluyor",
        "state.safe": "Güvenli",
        "state.warned": "Uyarı",
        "state.enforcing": "Zorlama",
        "timeline.detect": "Sapma",
        "timeline.warn": "Uyarı · 1 kez",
        "timeline.enforce": "Kilit",
        "countdown.remaining": "kalan",

        "menubar.tooltip.safe": "Pil güvenli aralıkta (%%%d–%%%d)",
        "menu.settings": "Ayarlar…",
        "menu.onboarding": "Tanıtımı Göster",
        "menu.quit": "Çıkış",

        "panel.title": "Battery Longer",
        "panel.healthy.charging.room": "Adaptörde, şarj oluyor. %%%2$d sınırına %1$d puan kaldı.",
        "panel.healthy.charging.atLimit": "Adaptörde. %%%d sınırında – şarjı çıkarma zamanı yaklaşıyor.",
        "panel.healthy.held": "Adaptörde, şarj akmıyor (macOS tutuyor). Sorun yok.",
        "panel.healthy.battery": "Pilde. %%%2$d sınırına %1$d puan var.",
        "panel.warned.body": "Bu tek uyarıdır. Süre bitince ekran kilitlenir.",
        "panel.enforcing.title": "Ekran kilitli · %@",
        "panel.enforcing.body": "%@ itibarıyla kilitli. Sadece durumu düzeltmek açar.",
        "stat.source": "Kaynak",
        "stat.source.adapter": "Adaptör",
        "stat.source.battery": "Pil",
        "stat.time": "Süre",
        "stat.cycles": "Döngü",
        "stat.health": "Sağlık",
        "panel.settings": "Ayarlar",
        "panel.rule.summary": "Kural %%%d–%%%d · süre %@",
        "panel.stats": "%d uyarı · %d kilit",
        "panel.quit": "Çıkış",
        "panel.quit.help": "Uygulamadan çık",
        "panel.quit.help.locked": "Kilit sırasında çıkış kapalıdır",

        "blocker.hint.over": "Kablo çıkınca bu ekran kendiliğinden kapanır.",
        "blocker.hint.under": "Adaptör takılınca bu ekran kendiliğinden kapanır.",
        "blocker.emergency.idle": "Acil çıkış · 5 sn basılı tut",
        "blocker.emergency.holding": "Basılı tut… %d",
        "blocker.emergency.note": "Bu, uygulamayı tamamen kapatır. Pil kuralını değil.",

        "onb.1.eyebrow": "Kural",
        "onb.1.title": "%20 – %80 arasında yaşa",
        "onb.1.body": "Lityum-iyon piller uçlarda yaşlanır. Sürekli %100'de tutmak ve sürekli %0'a indirmek, hücrelerin kimyasal ömrünü hızla tüketir. Bu uygulama pilini bu güvenli banda hapseder.",
        "onb.1.b1": "Adaptörde %80'e gelince → şarjı çıkar",
        "onb.1.b2": "Pilde %20'ye inince → şarjı tak",
        "onb.1.b3": "Dar bir bantta ayarlanabilir; pazarlık yoktur",
        "onb.2.eyebrow": "Adım 1",
        "onb.2.title": "Bir kez uyarır, 2 dakika verir",
        "onb.2.body": "Sınırı geçtiğin an menü çubuğu turuncuya döner, tek bir bildirim gelir ve 2:00 dakikalık geri sayım başlar. İkinci uyarı yoktur; erteleme yoktur.",
        "onb.2.b1": "Tek bildirim, tek ses",
        "onb.2.b2": "Menü çubuğunda canlı geri sayım",
        "onb.2.b3": "Süre içinde düzeltirsen hiçbir şey olmaz",
        "onb.3.eyebrow": "Adım 2",
        "onb.3.title": "Sonra zorlar",
        "onb.3.body": "2 dakika bitti ve hâlâ sınır dışındaysan tüm ekranlar kilitlenir. Kapat düğmesi yoktur. Kabloyu çıkardığın (veya taktığın) an kilit kendiliğinden kalkar.",
        "onb.3.b1": "Tüm ekranlarda, tüm masaüstlerinde",
        "onb.3.b2": "Uygulama değiştirme kapalı",
        "onb.3.b3": "Tek çıkış: pil aralığa dönsün",
        "onb.4.eyebrow": "Sonuç",
        "onb.4.title": "Yıllarca sağlıklı pil",
        "onb.4.body": "Bu disiplin sıkıcı görünür; ama %20–%80 bandında kalan piller, tam döngü yapanlara göre kat kat daha fazla döngü ömrü sunar. MacBook'un yıllar sonra da saatlerce dayansın.",
        "onb.4.b1": "Sadece MacBook'larda çalışır",
        "onb.4.b2": "Menü çubuğunda yaşar, Dock'ta yer kaplamaz",
        "onb.4.b3": "Bildirim izni: uyarıyı görebilmen için",
        "onb.back": "Geri",
        "onb.next": "İleri",
        "onb.finish": "Anladım, koru",

        "settings.title": "Battery Longer Ayarları",
        "settings.rule": "Kural",
        "settings.rule.low": "Alt sınır",
        "settings.rule.low.desc": "Pilde bu seviyeye inince → şarjı tak",
        "settings.rule.high": "Üst sınır",
        "settings.rule.high.desc": "Adaptörde bu seviyeye gelince → şarjı çıkar",
        "settings.rule.note": "Önerilen ve varsayılan: %%%d–%%%d. Aralık en az %d puan olmalı.",
        "settings.rule.reset": "Varsayılana dön",
        "settings.timing": "Süre",
        "settings.timing.grace": "Uyarıdan kilide süre",
        "settings.timing.grace.desc": "1 – 10 dakika, 30 sn adımlarla. Varsayılan 2:00.",
        "settings.timing.active": "Şu an bir uyarı aktif; yeni süre bir sonraki uyarıda geçerli olur.",
        "settings.warning": "Uyarı",
        "settings.warning.sound": "Uyarıda ses çal",
        "settings.warning.sound.desc": "Tek bir sistem sesi; sonrası sessizdir.",
        "settings.warning.panel": "Uyarıda paneli otomatik aç",
        "settings.warning.panel.desc": "Menü çubuğu paneli geri sayımla birlikte belirir.",
        "settings.warning.permission": "Bildirim izni",
        "settings.warning.permission.desc": "Uyarı bildirimi için macOS izni gerekir.",
        "settings.warning.openSystem": "Sistem Ayarları'nı aç",
        "settings.enforce": "Zorlama",
        "settings.enforce.sleep": "Alt sınır kilidinde Mac'i uyut",
        "settings.enforce.sleep.desc": "Kilit ekranı göründükten 4 sn sonra sistem uykuya alınır; kalan yüzde korunur.",
        "settings.enforce.snooze": "Erteleme / ikinci uyarı",
        "settings.enforce.snooze.desc": "Tasarım gereği yoktur. Tek çıkış, pilin aralığa dönmesidir.",
        "settings.enforce.off": "Kapalı",
        "settings.general": "Genel",
        "settings.general.login": "Girişte başlat",
        "settings.general.login.desc": "Koruma ancak uygulama çalışıyorsa vardır.",
        "settings.general.percent": "Menü çubuğunda yüzdeyi göster",
        "settings.general.percent.desc": "Kapalıyken yalnızca simge; uyarı ve kilitte geri sayım yine görünür.",
        "settings.general.language": "Dil",
        "settings.general.onboarding": "Tanıtım",
        "settings.general.onboarding.show": "Tekrar göster",
        "settings.stats": "İstatistik",
        "settings.stats.warnings": "Uyarı sayısı",
        "settings.stats.locks": "Kilit sayısı",
        "settings.stats.reset": "Sayaçları sıfırla",
        "settings.footer": "Battery Longer %@ · Sadece MacBook",

        "banner.eyebrow": "Tanıtım",
        "banner.title": "Battery Longer nasıl çalışır?",
        "banner.subtitle": "%20–%80 kuralı, tek uyarı ve kilit — eskizlerle bir dakikalık tur.",
        "banner.cta": "Turu başlat",
        "about": "Hakkında",
        "about.author": "Geliştirici",
        "about.company": "Firma",
        "about.source": "Kaynak kod",

        "notif.warn.title": "Battery Longer • %@",
        "notif.warn.subtitle": "Pil %%%d",
        "notif.warn.body": "%@ %@ içinde düzeltilmezse ekran kilitlenir.",
        "notif.resolved.title": "Battery Longer • Teşekkürler",
        "notif.resolved.body": "Pil tekrar güvenli aralıkta (%%%d).",

        "alert.notMacBook.title": "Bu uygulama sadece MacBook'larda çalışır",
        "alert.notMacBook.body": "Algılanan cihaz: %@. Dahili pil bulunamadı; %%20–%%80 kuralının masaüstü Mac'lerde anlamı yok. Uygulama kapanacak.",
        "alert.close": "Kapat",
    ]
}
