import Foundation

extension Strings {
    static let ja: [String: String] = [
        "lang.system": "システム",

        "violation.over.title": "充電器を外してください",
        "violation.under.title": "充電器を接続してください",
        "violation.over.instruction": "バッテリーが %d%% の上限に達しました。バッテリー寿命を守るため、今すぐ MacBook を電源から外してください。",
        "violation.under.instruction": "バッテリーが %d%% の下限を下回りました。深放電はセルを傷めます。今すぐ MacBook を充電してください。",

        "gauge.safe": "安全範囲",
        "state.held": "保持中",
        "state.safe": "安全",
        "state.warned": "警告",
        "state.enforcing": "ロック",
        "timeline.detect": "逸脱",
        "timeline.warn": "警告・1回のみ",
        "timeline.enforce": "ロック",
        "countdown.remaining": "残り",

        "menubar.tooltip.safe": "バッテリーは安全範囲内です（%d〜%d%%）",
        "menu.settings": "設定…",
        "menu.onboarding": "イントロダクションを表示",
        "menu.quit": "終了",

        "panel.title": "Battery Longer",
        "panel.healthy.charging.room": "電源接続中・充電中。%2$d%% の上限まであと %1$d ポイント。",
        "panel.healthy.charging.atLimit": "電源接続中。%d%% の上限です。もうすぐ外す時間です。",
        "panel.healthy.held": "電源接続中・充電停止（macOS が保持）。問題ありません。",
        "panel.healthy.battery": "バッテリー駆動中。%2$d%% の下限まであと %1$d ポイント。",
        "panel.warned.body": "これが唯一の警告です。時間切れで画面がロックされます。",
        "panel.enforcing.title": "画面ロック中・%@",
        "panel.enforcing.body": "%@ から。バッテリーの状態を直すことだけが解除の方法です。",
        "stat.source": "電源",
        "stat.source.adapter": "アダプタ",
        "stat.source.battery": "バッテリー",
        "stat.time": "時間",
        "stat.cycles": "サイクル",
        "stat.health": "状態",
        "capacity.title": "容量",
        "capacity.value": "%@ / %@ mAh",
        "capacity.design": "設計 %@ mAh",
        "capacity.lost": "−%@ mAh 劣化",
        "capacity.likeNew": "新品同様",
        "capacity.help": "濃い部分：現在の充電量 · 薄い部分：現在の満充電容量 · 背景：工場出荷時の設計容量",
        "panel.settings": "設定",
        "panel.rule.summary": "ルール %d〜%d%%・猶予 %@",
        "panel.stats": "警告 %d 回・ロック %d 回",
        "panel.quit": "終了",
        "panel.quit.help": "アプリを終了",
        "panel.quit.help.locked": "ロック中は終了できません",

        "blocker.hint.over": "ケーブルを外すと、この画面は自動的に閉じます。",
        "blocker.hint.under": "アダプタを接続すると、この画面は自動的に閉じます。",
        "blocker.emergency.idle": "緊急終了・5秒長押し",
        "blocker.emergency.holding": "そのまま押し続けて… %d",
        "blocker.emergency.note": "アプリを完全に終了します。ルールは変わりません。",

        "onb.1.eyebrow": "ルール",
        "onb.1.title": "20%〜80% の間で使う",
        "onb.1.body": "リチウムイオン電池は両端で劣化します。常に 100% で保つことや 0% まで使い切ることは、セルの化学的寿命を急速に消費します。このアプリはバッテリーを安全な帯域に閉じ込めます。",
        "onb.1.b1": "電源接続中に 80% → 充電器を外す",
        "onb.1.b2": "バッテリー駆動で 20% → 充電器を接続",
        "onb.1.b3": "狭い範囲で調整可能、交渉の余地なし",
        "onb.2.eyebrow": "ステップ 1",
        "onb.2.title": "警告は一度、猶予は 2 分",
        "onb.2.body": "上限を超えた瞬間、メニューバーがオレンジになり、通知が一度だけ届き、2:00 のカウントダウンが始まります。二度目の警告もスヌーズもありません。",
        "onb.2.b1": "通知は一度、サウンドも一度",
        "onb.2.b2": "メニューバーにライブカウントダウン",
        "onb.2.b3": "時間内に直せば何も起きません",
        "onb.3.eyebrow": "ステップ 2",
        "onb.3.title": "その後は強制",
        "onb.3.body": "2 分が過ぎてもまだ範囲外なら、すべての画面がロックされます。閉じるボタンはありません。ケーブルを外す（または接続する）とロックは自動的に解除されます。",
        "onb.3.b1": "すべてのディスプレイ、すべての操作スペースで",
        "onb.3.b2": "アプリの切り替えは無効",
        "onb.3.b3": "唯一の出口：バッテリーを範囲内に戻す",
        "onb.4.eyebrow": "結果",
        "onb.4.title": "何年も健康なバッテリー",
        "onb.4.body": "面倒に見えますが、20〜80% の帯域で使うバッテリーは、満充電と空を繰り返すものより何倍も多くのサイクルを保ちます。数年後も MacBook が何時間も持つように。",
        "onb.4.b1": "MacBook のみで動作",
        "onb.4.b2": "メニューバーに常駐、Dock にアイコンなし",
        "onb.4.b3": "通知の許可：警告を見逃さないために",
        "onb.back": "戻る",
        "onb.next": "次へ",
        "onb.finish": "了解、守ってもらう",

        "settings.title": "Battery Longer の設定",
        "settings.rule": "ルール",
        "settings.rule.low": "下限",
        "settings.rule.low.desc": "バッテリー駆動でこの値 → 充電器を接続",
        "settings.rule.high": "上限",
        "settings.rule.high.desc": "電源接続中にこの値 → 充電器を外す",
        "settings.rule.note": "推奨・デフォルト：%d〜%d%%。帯域は %d ポイント以上必要です。",
        "settings.rule.reset": "デフォルトに戻す",
        "settings.timing": "猶予",
        "settings.timing.grace": "警告からロックまで",
        "settings.timing.grace.desc": "1〜10 分、30 秒刻み。デフォルト 2:00。",
        "settings.timing.active": "警告が進行中です。新しい猶予は次回から適用されます。",
        "settings.warning": "警告",
        "settings.warning.sound": "サウンドを再生",
        "settings.warning.sound.desc": "システムサウンドを一度だけ。その後は無音です。",
        "settings.warning.panel": "パネルを自動で開く",
        "settings.warning.panel.desc": "メニューバーのパネルがカウントダウンとともに表示されます。",
        "settings.warning.permission": "通知の許可",
        "settings.warning.permission.desc": "警告通知には macOS の許可が必要です。",
        "settings.warning.openSystem": "システム設定を開く",
        "settings.enforce": "強制",
        "settings.enforce.sleep": "下限ロック時に Mac をスリープ",
        "settings.enforce.sleep.desc": "ロック画面表示の 4 秒後にスリープします。残量が保たれます。",
        "settings.enforce.snooze": "スヌーズ / 二度目の警告",
        "settings.enforce.snooze.desc": "設計上ありません。唯一の出口はバッテリーを範囲内に戻すことです。",
        "settings.enforce.off": "オフ",
        "settings.general": "一般",
        "settings.general.login": "ログイン時に起動",
        "settings.general.login.desc": "保護はアプリが動作している間だけ有効です。",
        "settings.general.percent": "メニューバーにパーセントを表示",
        "settings.general.percent.desc": "オフの場合はアイコンのみ。警告・ロック中はカウントダウンが表示されます。",
        "settings.general.language": "言語",
        "settings.general.onboarding": "イントロダクション",
        "settings.general.onboarding.show": "もう一度表示",
        "settings.stats": "統計",
        "settings.stats.warnings": "警告回数",
        "settings.stats.locks": "ロック回数",
        "settings.stats.reset": "カウンターをリセット",
        "settings.footer": "Battery Longer %@・MacBook 専用",

        "banner.eyebrow": "イントロダクション",
        "banner.title": "Battery Longer の仕組みを見る",
        "banner.subtitle": "20〜80 ルール、一度だけの警告、そしてロック。スケッチで巡る 1 分間のツアー。",
        "banner.cta": "ツアーを開始",
        "about": "このアプリについて",
        "about.author": "開発者",
        "about.company": "会社",
        "about.source": "ソースコード",

        "notif.warn.title": "Battery Longer • %@",
        "notif.warn.subtitle": "バッテリー %d%%",
        "notif.warn.body": "%@ %@ 以内に直さないと画面がロックされます。",
        "notif.resolved.title": "Battery Longer • ありがとう",
        "notif.resolved.body": "バッテリーが安全範囲に戻りました（%d%%）。",

        "alert.notMacBook.title": "このアプリは MacBook でのみ動作します",
        "alert.notMacBook.body": "検出されたデバイス：%@。内蔵バッテリーが見つかりません。20〜80 ルールはデスクトップ Mac では意味を持ちません。アプリを終了します。",
        "alert.close": "閉じる",
    ]
}
