import Foundation

/// English is the reference table: every key used in the app must exist here.
/// Strings with arguments use `String(format:)` placeholders; a literal percent sign is `%%`.
enum Strings {
    static let en: [String: String] = [
        "lang.system": "System",

        // Rule / violations
        "violation.over.title": "Unplug the charger",
        "violation.under.title": "Plug in the charger",
        "violation.over.instruction": "The battery reached the %d%% limit. Unplug your MacBook now to protect battery life.",
        "violation.under.instruction": "The battery dropped below the %d%% limit. Deep discharge damages the cells — plug your MacBook in now.",

        // Gauge / pills / timeline
        "gauge.safe": "safe range",
        "state.held": "Held",
        "state.safe": "Safe",
        "state.warned": "Warning",
        "state.enforcing": "Enforcing",
        "timeline.detect": "Deviation",
        "timeline.warn": "Warning · once",
        "timeline.enforce": "Lock",
        "countdown.remaining": "left",

        // Menu bar
        "menubar.tooltip.safe": "Battery within the safe range (%d–%d%%)",
        "menu.settings": "Settings…",
        "menu.onboarding": "Show Introduction",
        "menu.quit": "Quit",

        // Panel
        "panel.title": "Battery Longer",
        "panel.healthy.charging.room": "On adapter, charging. %d points to the %d%% limit.",
        "panel.healthy.charging.atLimit": "On adapter. At the %d%% limit — time to unplug is near.",
        "panel.healthy.held": "On adapter, not charging (held by macOS). All good.",
        "panel.healthy.battery": "On battery. %d points above the %d%% limit.",
        "panel.warned.body": "This is the only warning. When time runs out, the screen locks.",
        "panel.enforcing.title": "Screen locked · %@",
        "panel.enforcing.body": "Started at %@. Only fixing the battery unlocks it.",
        "stat.source": "Source",
        "stat.source.adapter": "Adapter",
        "stat.source.battery": "Battery",
        "stat.time": "Time",
        "stat.cycles": "Cycles",
        "stat.health": "Health",
        "panel.settings": "Settings",
        "panel.rule.summary": "Rule %d–%d%% · grace %@",
        "panel.stats": "%d warnings · %d locks",
        "panel.quit": "Quit",
        "panel.quit.help": "Quit the app",
        "panel.quit.help.locked": "Quit is disabled while locked",

        // Blocker
        "blocker.hint.over": "This screen closes by itself once the cable is out.",
        "blocker.hint.under": "This screen closes by itself once the adapter is connected.",
        "blocker.emergency.idle": "Emergency exit · hold 5 s",
        "blocker.emergency.holding": "Keep holding… %d",
        "blocker.emergency.note": "This quits the app entirely. Not the rule.",

        // Onboarding
        "onb.1.eyebrow": "The rule",
        "onb.1.title": "Live between 20% and 80%",
        "onb.1.body": "Lithium-ion batteries age at the extremes. Sitting at 100% and draining to 0% burns through the cells' chemical lifespan. This app confines your battery to the safe band.",
        "onb.1.b1": "At 80% on the adapter → unplug",
        "onb.1.b2": "At 20% on battery → plug in",
        "onb.1.b3": "Adjustable within a narrow band; no negotiation",
        "onb.2.eyebrow": "Step 1",
        "onb.2.title": "One warning, two minutes",
        "onb.2.body": "The moment you cross the limit, the menu bar turns orange, a single notification arrives and a 2:00 countdown starts. There is no second warning and no snooze.",
        "onb.2.b1": "One notification, one sound",
        "onb.2.b2": "Live countdown in the menu bar",
        "onb.2.b3": "Fix it in time and nothing happens",
        "onb.3.eyebrow": "Step 2",
        "onb.3.title": "Then it enforces",
        "onb.3.body": "Two minutes are up and you are still out of range? Every screen locks. There is no close button. The moment you unplug (or plug in), the lock lifts by itself.",
        "onb.3.b1": "On every display, every Space",
        "onb.3.b2": "App switching disabled",
        "onb.3.b3": "The only exit: battery back in range",
        "onb.4.eyebrow": "Result",
        "onb.4.title": "Years of healthy battery",
        "onb.4.body": "The discipline looks tedious, but batteries kept in the 20–80 band deliver many times more cycles than those run full-to-empty. Let your MacBook still last for hours years from now.",
        "onb.4.b1": "Runs on MacBooks only",
        "onb.4.b2": "Lives in the menu bar, no Dock icon",
        "onb.4.b3": "Notification permission: so you can see the warning",
        "onb.back": "Back",
        "onb.next": "Next",
        "onb.finish": "Got it, protect me",

        // Settings
        "settings.title": "Battery Longer Settings",
        "settings.rule": "Rule",
        "settings.rule.low": "Lower limit",
        "settings.rule.low.desc": "On battery, at this level → plug in",
        "settings.rule.high": "Upper limit",
        "settings.rule.high.desc": "On adapter, at this level → unplug",
        "settings.rule.note": "Recommended and default: %d–%d%%. The band must be at least %d points.",
        "settings.rule.reset": "Reset to defaults",
        "settings.timing": "Timing",
        "settings.timing.grace": "Warning to lock",
        "settings.timing.grace.desc": "1 – 10 minutes in 30 s steps. Default 2:00.",
        "settings.timing.active": "A warning is active; the new duration applies to the next one.",
        "settings.warning": "Warning",
        "settings.warning.sound": "Play a sound",
        "settings.warning.sound.desc": "A single system sound; silence afterwards.",
        "settings.warning.panel": "Open the panel automatically",
        "settings.warning.panel.desc": "The menu bar panel appears with the countdown.",
        "settings.warning.permission": "Notification permission",
        "settings.warning.permission.desc": "macOS permission is required for the warning notification.",
        "settings.warning.openSystem": "Open System Settings",
        "settings.enforce": "Enforcement",
        "settings.enforce.sleep": "Sleep the Mac on a lower-limit lock",
        "settings.enforce.sleep.desc": "4 s after the lock screen appears the system sleeps; the remaining charge is preserved.",
        "settings.enforce.snooze": "Snooze / second warning",
        "settings.enforce.snooze.desc": "None, by design. The only way out is the battery returning to range.",
        "settings.enforce.off": "Off",
        "settings.general": "General",
        "settings.general.login": "Launch at login",
        "settings.general.login.desc": "Protection exists only while the app is running.",
        "settings.general.percent": "Show percentage in the menu bar",
        "settings.general.percent.desc": "Icon only when off; the countdown still shows during warnings and locks.",
        "settings.general.language": "Language",
        "settings.general.onboarding": "Introduction",
        "settings.general.onboarding.show": "Show again",
        "settings.stats": "Statistics",
        "settings.stats.warnings": "Warnings",
        "settings.stats.locks": "Locks",
        "settings.stats.reset": "Reset counters",
        "settings.footer": "Battery Longer %@ · MacBook only",

        // Banner & about
        "banner.eyebrow": "Introduction",
        "banner.title": "See how Battery Longer works",
        "banner.subtitle": "The 20–80 rule, the single warning and the lock — a one-minute tour with sketches.",
        "banner.cta": "Start the tour",
        "about": "About",
        "about.author": "Developer",
        "about.company": "Company",
        "about.source": "Source code",

        // Notifications
        "notif.warn.title": "Battery Longer • %@",
        "notif.warn.subtitle": "Battery %d%%",
        "notif.warn.body": "%@ If not fixed within %@, the screen locks.",
        "notif.resolved.title": "Battery Longer • Thank you",
        "notif.resolved.body": "Battery is back in the safe range (%d%%).",

        // Alerts
        "alert.notMacBook.title": "This app only runs on MacBooks",
        "alert.notMacBook.body": "Detected device: %@. No internal battery found; the 20–80 rule is meaningless on desktop Macs. The app will quit.",
        "alert.close": "Close",
    ]
}
